[profile.default]
ffi = true
remappings = [
    "forge-std=lib/forge-std/src/",
    "foundry-huff=lib/foundry-huff/src/",
    "huffmate=lib/huffmate/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
gas_reports = ["Staking", "Pausable"]
solc = "0.8.15"
